name: Release

on:
  push:
    tags: ["*"]

permissions:
  contents: read

jobs:
  publish:
    name: Publish to hex.pm
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: versions
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{steps.versions.outputs.elixir}}
          otp-version: ${{ steps.versions.outputs.erlang}}
      - name: Restore dependencies cache
        uses: buildjet/cache@v3
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-mix-v6-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-v6-
      - name: Install dependencies
        run: mix deps.get
      - name: Check Formatting
        run: mix format --check-formatted
      - name: Check Compile Warnings
        run: mix compile --warnings-as-errors --all-warnings
      - name: Check Credo Warnings
        run: mix credo --strict
      - name: Write env file
        run: |
          touch .env.test
          echo XTB_API_URL="${{ secrets.XTB_API_URL }}" >> .env.test
          echo XTB_API_USERNAME="${{ secrets.XTB_API_USERNAME }}" >> .env.test
          echo XTB_API_PASSWORD="${{ secrets.XTB_API_PASSWORD }}" >> .env.test        
      - name: Run tests
        env:
          MIX_ENV: test
        run: mix test --max-failures 1 --warnings-as-errors
      - name: Check Dialyzer
        run: mix dialyzer
      - name: Generate documentation
        run: mix docs
      - name: Publish
        run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}

env:
  MIX_ENV: prod
